# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Optionally, add any additional configuration or scripts if needed
# COPY ./path/to/custom-scripts /docker-entrypoint-initdb.d
