CREATE TABLE comment
(
    id          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    username    VARCHAR(255),
    post_id     BIGINT,
    content     TEXT
);
