server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myusername
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    table: flyway_schema_history
    url: jdbc:postgresql://localhost:5432/mydatabase
    user: myusername
    password: mypassword

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: clientid
#            authorization-grant-type: authorization_code
#            scope: openid
#            client-secret: KL9spAwc2iVyWV6lLfAcS6W9sC1pITYW
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/course-whisperer
#            authorization-uri: http://localhost:8080/realms/course-whisperer/protocol/openid-connect/auth
#            token-uri: http://localhost:8080/realms/course-whisperer/protocol/openid-connect/token

springdoc:
  paths-to-match: /api/**