spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: root
    password: mkulo

  flyway:
    url: jdbc:postgresql://localhost:5432/mydatabase
    user: myuser
    password: mypassword
    enabled: true

springdoc:
  paths-to-match: /api/**